version: '3.9'
services:
  aaida-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      TWITTER_CLIENT_ID: twitterClientIdExample
      TWITTER_CLIENT_SECRET: twitterClientSecretExample
      TENSORFLOW_BASE_URL: http://tensorflow-serving:8501

  tensorflow-serving:
    image: gcr.io/bangkit-aaida/tensorflow-serving:v0.0.4
    ports:
      - "8500:8500"
      - "8501:8501"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: simplepassword
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - .data/postgresql/data:/var/lib/postgresql/data
      