kind: Deployment
apiVersion: apps/v1
metadata:
  name: aaida-backend-production
  labels:
    app: aaida-backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: aaida-backend
  template:
    metadata:
      name: backend
      labels:
        app: aaida-backend
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/bangkit-aaida/aaida-backend:v0.0.4
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: COMPONENT
          value: backend
        - name: VERSION
          value: production
        ports:
        - name: backend
          containerPort: 8080
