apiVersion: v1
kind: Service
metadata:
  labels:
    app: tensorflow-serving
  name: tensorflow-serving
spec:
  ports:
  - name: grpc
    port: 8500
    protocol: TCP
    targetPort: 8500
  - name: rest
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: tensorflow-serving
  sessionAffinity: None
  type: LoadBalancer
