steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'cc/k8s/*', 'gs://bangkit-aaida-kubernetes-manifests']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/bangkit-aaida/aaida-backend:$TAG_NAME', './cc/aaida-backend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/bangkit-aaida/aaida-backend:$TAG_NAME']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'aaida-backend', '--image', 'gcr.io/bangkit-aaida/aaida-backend:$TAG_NAME', '--region', 'asia-southeast1', '--platform', 'managed']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'gs://bangkit-aaida-model/*', 'cc/tensorflow-serving/model']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/bangkit-aaida/tensorflow-serving:$TAG_NAME', './cc/tensorflow-serving']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/bangkit-aaida/tensorflow-serving:$TAG_NAME']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'tensorflow-serving', '--image', 'gcr.io/bangkit-aaida/tensorflow-serving:$TAG_NAME', '--region', 'asia-southeast1', '--platform', 'managed']

images: ['gcr.io/bangkit-aaida/aaida-backend:$TAG_NAME', 'gcr.io/bangkit-aaida/tensorflow-serving:$TAG_NAME']
